export const ADD_SIMPLE_TOAST = 'ADD_SIMPLE_TOAST';
export const CLEAR_SIMPLE_TOAST = 'CLEAR_SIMPLE_TOAST';
export const TOAST_ON_DESTROY = 'TOAST_ON_DESTROY';
export const TOAST_OKAY_ACTION = 'TOAST_OKAY_ACTION';
export const TOAST_DENY_ACTION = 'TOAST_DENY_ACTION';
